### ISSUE TITLE
Stable item IDs

### ISSUE THREAD

**Issue by krlmlr** [ramnathv/htmlwidgets#107]
Autogenerated item IDs seem to be random numbers ([code reference](https://github.com/ramnathv/htmlwidgets/blob/09b933113ada170dacd01f609963dee89d349e97/R/htmlwidgets.R#L52)). When a widget is embedded in an HTML document, the ID is reassigned every time. Even if the random seed is reset in the beginning of the document, unrelated changes can lead to a change in the widget IDs for the entire document.

How about using a hash of the data instead:

```
id <- paste("htmlwidget", digest::digest(x), sep="-")
```

Slightly related: https://github.com/rstudio/DT/issues/72

**Comment by yihui** [comment]
This also bothered me since I had to commit bogus changes in GIT. `set.seed()` may help a little bit, e.g. https://github.com/rstudio/DT/blob/gh-pages/compile.R#L1

**Comment by krlmlr** [comment]
Yes, `set.seed()` helps most of the time, but not always. (Think about replacing an instance of `sample(1)` in the beginning of your document with `sample(2)`.) Do you think the hashes of the `x` objects are stable? (A similar approach could be explored for unnamed `knitr` chunks.)

**Comment by yihui** [comment]
I know what you mean. Perhaps I don't hate bogus changes as much as you do :)

You may see if we can get rid of the id in htmlwidgets. I don't completely understand what elementId is for, and if it is only for getting the resizing info, I guess we may be able not to use the id (instead, look for the next `<script type="application/htmlwidget-sizing>`).

**Comment by krlmlr** [comment]
At least with `DT` the ID is used to determine where the data goes:

```
<div id="datatable-1" class="datatables"/>
<script type="application/json" data-for="datatable-1">...
```

If I remove the `data-for` attribute, the table is not shown in the browser. (To me, it would have been a big surprise if it had worked.)

**Comment by ramnathv** [comment]
I see the issue with randomly set ids. However, having an `id` attribute is key for any post-processing you might want to do. I use it routinely to send messages from one widget to another. Note that the `createWidget` function provides an `elementId` parameter which you can use to set your own custom ids instead of relying on the randomized mechanism.

Having said that, I like the idea proposed by @krlmlr of using hashes to generate the id. @jcheng5 @jjallaire @timelyportfolio do you see any potential drawbacks of using `digest::digest(x)` to compute ids. One issue could be the computational time for `digest` when `x` is large. But that may be a non-issue given that the bottleneck with big data might be different.

**Comment by ramnathv** [comment]
I am closing this issue, since `createWidget` already provides for an `elementId` parameter. It is upto widget authors to expose this parameter in their widget constructor functions.
