### ISSUE TITLE
htmlwidget does not render when called from inside another function

### ISSUE THREAD

**Issue by skyebend** [ramnathv/htmlwidgets#150]
My html widget renders fine if I call it directly from the console, but does not appear in the RStudio plot window when it is called inside a larger data formatting function.  Oddly, it *does* appear if I add a browser() line in the enclosing function and then execute the line in the debugger console - which should be the identical R environment.  I'm hoping someone might have an idea where I could look for debugging this. I've tried examining the state of interactive() (always true).  Perhaps there is some state of the RStudio viewer that is different?

**Comment by jcheng5** [comment]
Widget functions don't render the widgets, they merely create and return them. If you call such functions at the R console, the console's default behavior for return values (that are not marked with `invisible()`) is to print them. So if your larger function is only intended to be used from the console, you can call `print()` on your widget value to get it to appear; but better would be if the widget could be returned as the return value of the larger function, so that it could be used in R Markdown documents as well.

**Comment by skyebend** [comment]
doh! works fine now, thanks.  this very obvious in hindsight, but might be worth mentioning in docs for clarity.  ?createWidget does say: Value.  "An object of class htmlwidget that will intelligently print itself into HTML in a variety of contexts including the R console, within R Markdown documents, and within Shiny output bindings."   But maybe the Details could explain that the returned value must be printed in order to display itself?
