### ISSUE TITLE
What is the "root" directory?

### ISSUE THREAD

**Issue by ivannp** [ramnathv/htmlwidgets#193]
I am trying to turn a js library into an htmlwidget. This library has a "images" sub-folder. For some reason the library doesn't seem to be able to find these images. I can setup the path explicitly, but whatever I have tried failed. For example, I tried referring to the directory as: htmlwidgets/lib/mylib/images, tried lib/mylib/images, mylib/images, images - nothing works. Any ideas what's going on?

**Comment by timelyportfolio** [comment]
Could you provide some context, such as an example, a repo with what you have done so far, or at a minimum the name of the JS library, so that we might be able to help?  I'm pretty sure I know the answer to the question but don't want to have to build a `htmlwidget` from scratch to demonstrate.

**Comment by ivannp** [comment]
The library is amcharts. I hooked it up so it already shows data in RStudio. As I said, it has a sub-folder called images. It has the ability to find the sub-folder, or it can be specified in some internal variables. Nothing works in R-studio.
Looking at my older prototype, from a year ago, I seem to have managed to get it working by adding an "attachment" file to the yaml. That doesn't work anymore, not to mention, it doesn't scale.

**Comment by jbkunst** [comment]
Hi @ivannp 

Maybe the [dataknowledge implementation](https://dataknowledge.github.io/introduction_ramcharts/index.html) can help you. They have an image folder https://github.com/DataKnowledge/rAmCharts/tree/master/inst/htmlwidgets/lib/images, not sure if they uses them and not sure if these images are what you want to use.

**Comment by timelyportfolio** [comment]
Thanks @jbkunst.  @ivannp, were you already aware of `rAmCharts` and just trying to learn `htmlwidgets`?  Looking at the @DataKnowledge implementation of `rAmCharts` would be a great learning experience although I'm not sure I would recommend the `refClass` approach.  There are lots of [examples](https://github.com/DataKnowledge/rAmCharts/tree/master/examples).

Just to show how it works, everything specified in `yaml` for `htmlwidgets` will be copied .  If you look at these [lines](https://github.com/DataKnowledge/rAmCharts/blob/master/inst/htmlwidgets/ramcharts_base.yaml#L4), everything in [this directory](https://github.com/DataKnowledge/rAmCharts/tree/master/inst/htmlwidgets/lib) will be copied and be available at `./lib/amcharts-3.18.2`.  Here is some code to play demonstrate.


```
# devtools::install_github("DataKnowledge/rAmCharts")

library(rAmCharts)
data(iris)
ah <- amHist(iris$Sepal.Length, freq = FALSE, col = "gray")
ah

# to show that the images are copied we can do something
#   like this
library(htmltools)

browsable(
  tagList(list(
    plot(ah),
    tags$img(
      height = 200, width = 200,
      src = "./lib/amcharts-3.18.2/images/dragIcon.gif"
    )
  ))
)
```

**Comment by ivannp** [comment]
The root caused of the problem is that the directory is RENAMED, in other words, the version is added to the runtime (amcharts becomes amcharts-3.14.2 when running under the server). Thus, if the library/app needs to refer to the directory (useful in amcharts) - it needs to provide the full path, which  complicates moving to new versions.

Notice how most htmlwidgets packages CHANGE the structure of the actual library by moving subdirectories as direct children of lib. Not a bad idea to document this somewhere.

**Comment by jjallaire** [comment]
It's not a good idea to refer directly to this path as when htmlwidgets are
included in a base64 encoded HTML file (which is the default for R
Markdown) all of those paths are gone. If you need a resource it's best to
include it somehow directly in the HEAD as part of your widget's dependency
declaration or to use attachment mechanism you mentioned before.

**Comment by timelyportfolio** [comment]
very good point @jjallaire

**Comment by ivannp** [comment]
In other words, the way to use libraries like amcharts, which have properties like "path" and "pathToImages" is by reshuffling their resources and praying that won't break them completely?

**Comment by ivannp** [comment]
In other words, the way to use libraries like amcharts, which have
properties like "path" and "pathToImages" is by reshuffling their resources
and praying that won't break them completely?

**Comment by jjallaire** [comment]
I'm sure there is a path to do what are looking for and no fragility or
"praying" will be necessary (over 50 JavaScript libraries have been
successfully wrapped with htmlwidgets). Self contained HTML is critical for
easy distribution of R Markdown documents created with htmlwidgets so this
is a fundamental design tenant.

The ways to get things embedded are:

1. Reference them in the <head> (you can add arbitrary <head> code as part
of your widget dependency declaration)

2. Reference them in a CSS file (pandoc will automatically embed them)

3. Use attachments

Stuff that's dynamically referenced in JavaScript is harder because pandoc
isn't able to parse the JavaScript for dependencies.

If you absolutely must have directories of assets as part of your widget
then you can still include them in the top-level directory of your widget
and they will be copied (references in JavaScript or CSS would need to be
relative). At this point your widget will only work in Shiny applications
or R Markdown documents with self_contained: false.

**Comment by ivannp** [comment]
For me using amcharts in Rmarkdown, or shiny is not an issue. Or at least not at this point. And it probably doesn't make sense based on what you are saying, because this library does have assets.

The point is that there are valid scenarios (a library like amcharts) where it would be useful if directories were not mocked with a version number. The fact that this is done by default, and was breaking the functionality of a perfectly valid js library, was what triggered this whole discussion. Doesn't it make sense to have an yaml option for not renaming the directory?

**Comment by jjallaire** [comment]
Every JavaScript library I know of can be located in any directory (i.e.
you can name the jquery directory anything you want including "jquery",
"jquery-1.10", "jquery-1.10.1"). I doubt there are libraries that must have
a given parent directory name.

For htmlwidgets the name of the library the dependency is copied to is
opaque *by design*. This is because in R Markdown it's all base64 encoded
assets (the directory is literally gone) and even in Shiny the directory
often includes an absolute path to the R package library folder (something
that can never be statically known).

**Comment by ivannp** [comment]
Was sure we are going to hit the "by design" wall at some point. Which makes the entire discussion started with:
> It's not a good idea to refer directly to this path as when htmlwidgets are included in a base64 encoded HTML file (which is the default for R Markdown) all of those paths are gone.
a waste of time.
