### ISSUE TITLE
Replace htmlwidgets by screenshots in vignettes

### ISSUE THREAD

**Issue by FrancoisGuillem** [ramnathv/htmlwidgets#274]
I'm writing a vignette for a package and it includes several leaflet maps. The vignette is too large so `R CMD CHECK` reports the following problem:

```
checking installed package size ... NOTE
  installed size is  5.2Mb
  sub-directories of 1Mb or more:
    doc   4.6Mb
```

I was wondering if there is an option to replace htmlwidgets by screenshots in package vignettes to reduce their size?

**Comment by ramnathv** [comment]
If I remember correctly @yihui uses a knitr hook in `blogdown` to embed screenshots of  `htmlwidgets` in pdf documents. I presume the same hook can be used to do what you are striving for.

**Comment by yihui** [comment]
@ramnathv That is unlikely to work on CRAN, because it depends on the webshot package, which in turn depends on PhantomJS. You cannot assume CRAN has PhantomJS installed.

@FrancoisGuillem Perhaps it sounds crazy, but what I'd recommend is to not use vignettes with complicated or large examples. Build your own website instead: https://github.com/rstudio/blogdown This way, you will not be limited by CRAN, or bring any pressure to CRAN. You can simply provide a link in your vignette pointing to your web page. If you need help, they can help you: https://github.com/rbind

**Comment by FrancoisGuillem** [comment]
Thank you for the reply. I will shorten my vignette and point to external resources.
