### ISSUE TITLE
Setting background in saveWidget() is broken in 1.0

### ISSUE THREAD

**Issue by Slanman3755** [ramnathv/htmlwidgets#297]
The body tag of widget after trying to set background in saveWidget():
```
<body style="margin: 0px; padding: 0px; overflow: hidden; width: 100%; height: 100%;" e8e8e8"="">E8E8E8;"&gt;
```
As you can see the background-color property is getting lost/destroyed.

**Comment by jjallaire** [comment]
@jcheng5 Is it possible that this commit is the culprit: https://github.com/ramnathv/htmlwidgets/commit/e53abc5988523b96a553a1390dcb62511c8c73b2

**Comment by jcheng5** [comment]
@Slanman3755 Thanks for the report. What does `rmarkdown::pandoc_version()` return?

**Comment by jcheng5** [comment]
Never mind, I get a repro on both 1.19.2.1 and 2.0.4. It looks like a background color beginning with `#` is interpreted as an h1 tag by pandoc. Maybe rather than fight with pandoc about it, we should translate the hex color to decimal `rgb(red, green, blue)` form--in this example, `background="rgb(232,232,232)"` seems to work fine.
