### ISSUE TITLE
saveWidget to a relative path

### ISSUE THREAD

**Issue by mariodejung** [ramnathv/htmlwidgets#299]
Just had the problem to save my widget into a subdirectory relative to my working directory. 
Is there a special reason, why relative paths do not work? I had a question on stack overflow for this https://stackoverflow.com/questions/48690837/saving-interactive-plotly-graph-to-a-path-using-htmlwidget/48691210

So in the end, absolute path works and as I figured out with an older issue here, by using `normalizePath()` it also works. Why not relative path form?

```
results_dir <- 'results'
if(!dir.exists(results_dir)) dir.create(results_dir)
p <- plotly::plot_ly(economics, x = ~date, y = ~pop, 
             type = 'scatter', mode = 'markers')
htmlwidgets::saveWidget(p, 
                        file.path(results_dir, 'VSGs.html'))
```

**Comment by malcook** [comment]
I too have stumbled over the fact that saveWidget which requires `file` to be in current working directory.  If it is not,  the error is raised:

  ```
Error in normalizePath(basepath, "/", TRUE) : 
  path[1]="my/Relative/Path": No such file or directory
```

My workaround is to use the following wrapper:

```
saveWidgetFix <- function (widget,file,...) {
  ## A wrapper to saveWidget which compensates for arguable BUG in
  ## saveWidget which requires `file` to be in current working
  ## directory.
  wd<-getwd()
  on.exit(setwd(wd))
  outDir<-dirname(file)
  file<-basename(file)
  setwd(outDir);
  saveWidget(widget,file=file,...)
}
```

**Comment by RylanSchaeffer** [comment]
Any update on this issue?

**Comment by kxshen** [comment]
Though relatively new to leaflet, I found this to be unintrusive and intuitive, using `with_dir()` native to R to bypass all of the working directory navigation errors in `saveWidget()`:

`withr::with_dir('results_directory', saveWidget(widget, file="filename.html"))
`

**Comment by cpsievert** [comment]
You can also use the `libdir` argument: `saveWidget(widget, file = 'filename.html', libdir = 'results_directory')`

To make this easier, perhaps `libdir` could default to `dirname(file)` (and `file <- basename(file)`)

**Comment by solarchemist** [comment]
Thanks for the suggested work-arounds! `with_dir()` was a little hit-and-miss,  but the `saveWidgetFix()` function worked alright in interactive mode at least. 

The `saveWidget()` function with or without the above suggestions is still practically unusable inside Rnw knitr chunks, though.  I'm not sure why--the HTML file on disk is simply never created, although every line of code appears to be executed (I checked by peppering almost every line with `message()`, and those were printed in the knitr output...)

Since this is a pretty old bug by now, may I suggest at least adding a big bold mention in the README and/or in the docs? Can be really frustrating for new users otherwise.

**Comment by gregrs-uk** [comment]
@cpsievert Thanks for fixing this.

Just a heads up that when using `selfcontained = TRUE` (the default), `saveWidget` should presumably remove the temporary directory it creates (as happens when you save in the current directory rather than a relative one). However, it leaves this temporary directory in place. I have used `unlink(stringr::str_replace(path, "\\.html", "_files"), recursive = TRUE)` to remove it. Happy to open a separate issue if helpful.

**Comment by cpsievert** [comment]
@gregrs-uk yes, please open a new issue, thanks!
