### ISSUE TITLE
Feeding the proper json-shaped data to d3pie

### ISSUE THREAD

**Issue by smartinsightsfromdata** [ramnathv/htmlwidgets#70]
I am trying to use htmlwidgets to create a simple package using the d3 library d3pie.
Frankly I've got much ahead much faster than what I would have expected: well done guys.

On the other hand while I manage to get the title & subtitle to show,  now I'm stuck with finding the correct json data shape for the d3pie library.
I've tried numerous variants but clearly I'm not succeeding.
This is the error I'm currently getting:
```javascript
not valid:  Object
label: "JavaScript"
value: "264131"
__proto__: Object
```
I need some help!
The package is here: https://github.com/smartinsightsfromdata/rd3pie
(please note I've not even started to think about how to render the pie in shiny, even if it is my final goal)

**Comment by jjallaire** [comment]
This various by JS library but we do have a couple of helper functions in the framework (documentation here: http://www.htmlwidgets.org/develop_advanced.html#data-transformation)

**Comment by smartinsightsfromdata** [comment]
I managed (after long battle!) to overcome the issue, but this makes me reflect on the general design goal of htmlwidgets.
I understand (from the documentation referred to above by jjallaire) that R data.frame representation is much faster over the network than the D3 representation.
On the other hand this forces the need to develop more complex javascript code.

Now the main goal of hmlwidgets is (as I understand it) to allow fast integration into R and shiny of javascript libraries implemented by people not massively expert in  javascript. This is sort of against the ambition to have also a "fast implementation".

At the very least it would be great to have the choice, making available and document dataframeToD3 type of function on the R side, leaving the developer to choose which direction to take (obviously somebody else can always come and do a better implementation: we live in a competitive world!). 

Many thanks again for this great package.

**Comment by timelyportfolio** [comment]
From my point of view, education (more vignettes, posts, and examples) will be the only way to solve this problem, and I think as you say this is critical since it will often be a common obstacle while building `htmlwidgets`.  @jeroenooms has done a very thorough job explaining the transformation in the `jsonlite` [Data Mapping](http://cran.r-project.org/web/packages/jsonlite/vignettes/json-mapping.pdf) vignette.  The easy and most common case of `data.frame` to convert in `JSON` to either an array of arrays (`columns`) or array of objects (`rows`) is already handled in `jsonlite` (see #28).

In terms of providing an option within `htmlwidgets`, this will be very tricky to cover the various formats required by Javascript libraries.  While working on `rCharts`, nearly every library (>10) that we wrapped had different structures required for the data.  Another complicating factor is the `htmlwidgets` author has a choice in how they separate or not separate data from config + settings.  Often the data will follow a different format than the settings, so blanket applying across both could easily present more issues.

Unfortunately, there is no easy solution.  I side with one consistent, standard, prebuilt way of sending data from R to JS.  If and when, `htmlwidgets` converts to `jsonlite`, I could support a `row`/`column` type option or argument, but beyond this I think we will end up a confusing array of options that will require more education and documentation than current.

**Comment by timelyportfolio** [comment]
on another note, this might help with `d3pie` http://timelyportfolio.github.io/rChartsExtra/d3pie/.  I'll have a look through your code.

**Comment by smartinsightsfromdata** [comment]
@timelyportfolio I could do this only thanks to your posts on d3pies! 
Thanks again.
