### ISSUE TITLE
jQuery check false but then uses `.filter` from jQuery

### ISSUE THREAD

**Issue by timelyportfolio** [ramnathv/htmlwidgets#84]
In a Shiny context, these [lines](https://github.com/ramnathv/htmlwidgets/blob/master/inst/www/htmlwidgets.js#L359-L362) call [lines](https://github.com/ramnathv/htmlwidgets/blob/master/inst/www/htmlwidgets.js#L23-L25) in which there is a check for jQuery

```
    if (typeof(jQuery) !== "undefined" && scope instanceof jQuery) {
      return scope.find(selector);
    }
    if (scope.querySelectorAll) {
      return scope.querySelectorAll(selector);
    }
```

This makes sense, but there are two issues.

1.  if no jQuery then scope is an "array", so `scope[0].querySelectorAll` will need to be used  
2.  on the `return`, this [line](https://github.com/ramnathv/htmlwidgets/blob/master/inst/www/htmlwidgets.js#L362) tries to use `filter` from jQuery, which of course will not work if jQuery is not available.

I discovered this because `rbokeh` https://github.com/bokeh/rbokeh/issues/25 uses jQuery, so the `jQuery` returns `false` even though it is really there.  This is another issue that I'm trying to address.

**Comment by jcheng5** [comment]
This doesn't sound right...

1. I think you're seeing an array because jQuery actually is loaded (as it always is in a Shiny context) but `jQuery` was clobbered or the instanceof check is failing. If jQuery isn't loaded, the only place this is called should be passing `documentElement` ([here](https://github.com/ramnathv/htmlwidgets/blob/921ba807c85404f6b8b16a8adb15c4401cf1a922/inst/www/htmlwidgets.js#L435)).
2. This code only executes in Shiny mode, where jQuery is guaranteed to be available.

Once rbokeh clobbers jQuery, I think we basically have to consider Shiny and htmlwidgets to have undefined behavior. I've seen that even simple event subscriptions don't work right once you've loaded two copies of jQuery. I strongly recommend that you NOT paper over the double-jQuery issue by trying to fix the specific symptoms called out in this bug, and instead see if you can come up with a PR for bokeh to unbundle these pieces.

**Comment by timelyportfolio** [comment]
I agree unbundling will be the only stable solution.

**Comment by timelyportfolio** [comment]
don't think there is any reason to keep this open. Thanks @jcheng5 for your help and clarification.
